services:

  solicitudes-db:
    image: postgres:15
    container_name: solicitudes-db
    restart: always
    environment:
      POSTGRES_DB: solicitudesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - solicitudes-data:/var/lib/postgresql/data
    networks:
      - solicitudes-net

  ms-solicitudes:
    build: .
    container_name: ms-solicitudes
    depends_on:
      - solicitudes-db
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://solicitudes-db:5432/solicitudesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_ENCODING: UTF-8
    networks:
      - solicitudes-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - solicitudes-db
    networks:
      - solicitudes-net

volumes:
  solicitudes-data:

networks:
  solicitudes-net: