spring.application.name=ms-solicitudes
server.port=8080

##############################################
# BASE DE DATOS DOCKER
##############################################
spring.datasource.url=jdbc:postgresql://solicitudes-db:5432/solicitudesdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

##############################################
# JPA
##############################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##############################################
# INICIALIZACION
##############################################
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

##############################################
# SEGURIDAD KEYCLOAK
##############################################
# 1. Validacion: Acepta tokens generados en tu PC (Postman/Localhost)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/tpi-backend

# 2. Conexion: Usa la red interna de Docker para buscar las llaves publicas
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs

##############################################
# SWAGGER
##############################################
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

##############################################
# ENCODING
##############################################
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

##############################################
# LOGGING
##############################################
logging.level.root=INFO
logging.level.ar.edu.utn.frc.backend.grupo114=DEBUG

# ==========================================
# LOGS DE SEGURIDAD (DEBUG)
# ==========================================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG