spring.application.name=ms-solicitudes
server.port=8080

# ========== BASE DE DATOS ==========
spring.datasource.url=jdbc:postgresql://solicitudes-db:5432/solicitudesdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========== ENCODING ==========
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# ========== INICIALIZACIÓN ==========
spring.sql.init.mode=never

# ========== SWAGGER ==========
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
